export enum Areas {
    STOICISM = "STOICISM",
    FINANCES = "FINANCES",
    HEALTH = "HEALTH",
    COMMUNITY = "COMMUNITY",
    CAREER = "CAREER",
    SPIRITUALITY = "SPIRITUALITY",
    FAMILY = "FAMILY",
    ZEN = "ZEN",
    TAOISM = "TAOISM",
    HUMANISM = "HUMANISM",
    EXISTENTIALISM = "EXISTENTIALISM",
    CONFUCIANISM = "CONFUCIANISM"
  }